"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./_lib/Header/Header";
import Footer from "./_lib/Footer/Footer";
import "./globals.css";
import useLocalStorage from "use-local-storage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const defaultDark =
    typeof window !== "undefined" &&
    window.matchMedia("(prefers-color-scheme: dark)").matches;

  const [theme, setTheme] = useLocalStorage(
    "theme",
    defaultDark ? "dark" : "light"
  );

  const availableThemes = ["light", "dark", "blue", "green"];
  return (
    <html lang="en" data-theme={theme}>
      <head>
        <title>Henry Nuñez</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header
          theme={theme}
          setTheme={setTheme}
          availableThemes={availableThemes}
        />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
